const STORE_KEY='vnbx-store-data-v1';let data=JSON.parse(localStorage.getItem(STORE_KEY)||'{"settings":{"adminPassword":"vnbx1234"},"categories":[],"products":[]}');let serverMode=false,editingId=null;const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n||0);const catName=id=>(data.categories||[]).find(c=>c.id===id)?.name||id||'Otros';
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})},credentials:'same-origin'});let body={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.error||`Error ${r.status}`);return body}
async function syncFromServer(){const remote=await api('/api/store?private=1');if(remote&&Array.isArray(remote.products)){data={...data,...remote,settings:{...data.settings,...(remote.settings||{}),...(remote.content||{})},categories:(remote.categories||[]).map((c,i)=>typeof c==='string'?{id:'cat-'+i,name:c,icon:'◇',order:i+1}:c)};localStorage.setItem(STORE_KEY,JSON.stringify(data))}}
async function persist(){localStorage.setItem(STORE_KEY,JSON.stringify(data));if(serverMode)await api('/api/store',{method:'PUT',body:JSON.stringify(data)})}
function showApp(){sessionStorage.setItem('vnbx-admin','1');$('#loginView').classList.add('hidden');$('#adminApp').classList.remove('hidden');renderAll()}
function renderAll(){renderProducts();renderCategories();fillSettings();const w=String(data.settings?.whatsapp||'').replace(/\D/g,'');$('#ordersWhatsapp').href=w?`https://wa.me/${w}`:'#'}
function renderProducts(){$('#productRows').innerHTML=(data.products||[]).map(p=>`<tr><td><div class="table-product"><img src="${p.images?.[0]||p.image||''}" alt=""><span>${p.name}</span></div></td><td>${catName(p.category)}</td><td>${money(p.price)}</td><td>${p.stock??0}</td><td><span class="status ${p.active!==false?'':'off'}">${p.active!==false?'Visible':'Oculto'}</span></td><td><button class="action-btn" data-edit="${p.id}">Editar</button></td></tr>`).join('')||'<tr><td colspan="6">Todavía no hay productos cargados.</td></tr>';document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.edit)))}
function renderCategories(){$('#categoryRows').innerHTML=(data.categories||[]).sort((a,b)=>(a.order||0)-(b.order||0)).map(c=>`<div class="category-row"><span class="drag">☷</span><span>${c.icon||'◇'}</span><strong>${c.name}</strong><small>Orden ${c.order||0}</small><button class="action-btn" data-cat-edit="${c.id}">Editar</button><button class="danger-btn" data-cat-del="${c.id}">Eliminar</button></div>`).join('')||'<p>Aún no hay categorías.</p>';document.querySelectorAll('[data-cat-edit]').forEach(b=>b.addEventListener('click',()=>editCategory(b.dataset.catEdit)));document.querySelectorAll('[data-cat-del]').forEach(b=>b.addEventListener('click',async()=>{if(confirm('¿Eliminar esta categoría?')){data.categories=data.categories.filter(c=>c.id!==b.dataset.catDel);await persist();renderCategories()}}))}
function fillSettings(){const f=$('#settingsForm'),s=data.settings||{};for(const el of f.elements)if(el.name&&s[el.name]!==undefined)el.value=s[el.name]||''}
async function saveSettings(){const f=new FormData($('#settingsForm'));data.settings=data.settings||{};for(const [key,value] of f.entries())data.settings[key]=value;await persist();alert(serverMode?'Configuración guardada en el servidor.':'Configuración guardada en este navegador.')}
function openProduct(id){editingId=id||null;const p=data.products.find(x=>x.id===id)||{id:'',name:'',category:data.categories[0]?.id||'',price:0,oldPrice:0,stock:0,description:'',images:[''],tags:[],active:true};const f=$('#productForm');$('#productDialogTitle').textContent=id?'Editar producto':'Nuevo producto';f.id.value=p.id;f.name.value=p.name;f.price.value=p.price??0;f.oldPrice.value=p.oldPrice||'';f.stock.value=p.stock??0;f.description.value=p.description||'';f.image.value=p.images?.[0]||p.image||'';f.tags.value=(p.tags||[]).join(', ');f.active.checked=p.active!==false;f.category.innerHTML=(data.categories||[]).map(c=>`<option value="${c.id}">${c.name}</option>`).join('');f.category.value=p.category||data.categories[0]?.id||'';$('#deleteProduct').style.visibility=id?'visible':'hidden';$('#productDialog').showModal()}
async function saveProduct(e){e.preventDefault();const f=new FormData(e.target),p={id:f.get('id')||'p'+Date.now(),name:f.get('name'),category:f.get('category'),price:Number(f.get('price')),oldPrice:Number(f.get('oldPrice')||0),stock:Number(f.get('stock')),description:f.get('description'),images:[f.get('image')||''],tags:String(f.get('tags')||'').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean),active:f.get('active')==='on'};const i=data.products.findIndex(x=>x.id===p.id);if(i>=0)data.products[i]=p;else data.products.push(p);await persist();$('#productDialog').close();renderProducts()}
async function login(){const password=$('#passwordInput').value;try{const status=await api('/api/auth/status');const result=await api(status.configured?'/api/auth/login':'/api/auth/setup',{method:'POST',body:JSON.stringify({password})});if(result.ok){serverMode=true;await syncFromServer();showApp();return}}catch(error){if(password===(data.settings?.adminPassword||'vnbx1234')){serverMode=false;showApp();return}$('#loginError').textContent=error.message||'No se pudo iniciar sesión.'}}
function init(){if(sessionStorage.getItem('vnbx-admin')==='1'){serverMode=true;syncFromServer().then(showApp).catch(()=>{serverMode=false;showApp()})}$('#loginForm').addEventListener('submit',e=>{e.preventDefault();login()});$('#logoutBtn').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}sessionStorage.removeItem('vnbx-admin');location.reload()});document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.admin-section').forEach(x=>x.classList.add('hidden'));$('#'+t.dataset.tab+'Tab').classList.remove('hidden')}));$('#newProduct').addEventListener('click',()=>openProduct());$('#productForm').addEventListener('submit',saveProduct);$('#closeProduct').addEventListener('click',()=>$('#productDialog').close());$('#deleteProduct').addEventListener('click',async()=>{if(editingId&&confirm('¿Eliminar este producto?')){data.products=data.products.filter(p=>p.id!==editingId);await persist();$('#productDialog').close();renderProducts()}});$('#newCategory').addEventListener('click',()=>$('#categoryDialog').showModal());$('#closeCategory').addEventListener('click',()=>$('#categoryDialog').close());$('#categoryForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);data.categories.push({id:'cat'+Date.now(),name:f.get('name'),icon:f.get('icon')||'◇',order:Number(f.get('order')||5)});await persist();$('#categoryDialog').close();e.target.reset();renderCategories()});$('#saveAll').addEventListener('click',saveSettings)}
async function editCategory(id){const c=data.categories.find(x=>x.id===id),name=prompt('Nombre de categoría',c.name);if(name){c.name=name;await persist();renderCategories()}}document.addEventListener('DOMContentLoaded',init);
